version: "3.8"

services:
  db:
    container_name: postgres-container
    image: postgres:14.0
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
    restart: always
    #    env_file:
    #      - .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data

#  backend:
#    container_name: back
#    build:
#      context: ./back
#    depends_on:
#      - db
#    restart: unless-stopped
#    ports:
#      - '${API_PORT}:3001'
#    environment:
#      - API_PORT=${API_PORT}
#      - API_HOST=${API_HOST}
#      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
#      - TYPEORM_USERNAME=${TYPEORM_USERNAME}
#      - TYPEORM_PASSWORD=${TYPEORM_PASSWORD}
#      - TYPEORM_DATABASE=${TYPEORM_DATABASE}
#      - TYPEORM_PORT=${TYPEORM_PORT}
#      - TYPEORM_HOST=db
