
FROM node:20-alpine as builder
WORKDIR /app
COPY /*.json ./
COPY .. .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY  --from=builder /app ./
EXPOSE 3001
cmd ["npm","run","start:prod"]






